program CamisasFelizes;

uses
  Vcl.Forms,
  uConexao in 'ConexãoBD\uConexao.pas',
  uConexaoSingleTon in 'ConexãoBD\uConexaoSingleTon.pas',
  uBase in 'Base\uBase.pas' {frmBase},
  uConsultaBase in 'Base\uConsultaBase.pas' {frmPesquisaBase},
  uPrincipal in 'Principal\uPrincipal.pas' {frmPrincipal},
  uClasseInterfaceViewBase in 'Base\uClasseInterfaceViewBase.pas',
  uInterfaceViewBase in 'Base\uInterfaceViewBase.pas',
  uInterfaceConsultaBase in 'Base\uInterfaceConsultaBase.pas',
  uClasseInterfaceConsultaBase in 'Base\uClasseInterfaceConsultaBase.pas',
  Vcl.Themes,
  Vcl.Styles,
  uConsultaUfController in 'CadastroUF\consulta\uConsultaUfController.pas',
  uConsultaUfForm in 'CadastroUF\consulta\uConsultaUfForm.pas' {ConsultaUfForm},
  uConsultaUfModel in 'CadastroUF\consulta\uConsultaUfModel.pas',
  uConsultaUfRegra in 'CadastroUF\consulta\uConsultaUfRegra.pas',
  uInterfaceConsultaUfModel in 'CadastroUF\consulta\uInterfaceConsultaUfModel.pas',
  uInterfaceUfModel in 'CadastroUF\consulta\uInterfaceUfModel.pas',
  uCadastroUfController in 'CadastroUF\cadastro\uCadastroUfController.pas',
  uCadastroUfDto in 'CadastroUF\cadastro\uCadastroUfDto.pas',
  uCadastroUfForm in 'CadastroUF\cadastro\uCadastroUfForm.pas' {CadastroUfForm},
  uCadastroUfModel in 'CadastroUF\cadastro\uCadastroUfModel.pas',
  uCadastroUfRegra in 'CadastroUF\cadastro\uCadastroUfRegra.pas',
  uInterfaceCadastroUfModel in 'CadastroUF\cadastro\uInterfaceCadastroUfModel.pas',
  uCadastroCorController in 'Cor\Cadastro\uCadastroCorController.pas',
  uCadastroCorDto in 'Cor\Cadastro\uCadastroCorDto.pas',
  uCadastroCorForm in 'Cor\Cadastro\uCadastroCorForm.pas' {CadastroCorForm},
  uCadastroCorModel in 'Cor\Cadastro\uCadastroCorModel.pas',
  uCadastroCorRegra in 'Cor\Cadastro\uCadastroCorRegra.pas',
  uInterfaceCadastroCorModel in 'Cor\Cadastro\uInterfaceCadastroCorModel.pas',
  uConsultaCorController in 'Cor\Consulta\uConsultaCorController.pas',
  uConsultaCorForm in 'Cor\Consulta\uConsultaCorForm.pas' {ConsultaCorForm},
  uConsultaCorModel in 'Cor\Consulta\uConsultaCorModel.pas',
  uConsultaCorRegra in 'Cor\Consulta\uConsultaCorRegra.pas',
  uInterfaceConsultaCorModel in 'Cor\Consulta\uInterfaceConsultaCorModel.pas',
  uInterfaceCorModel in 'Cor\Consulta\uInterfaceCorModel.pas',
  uCadastroTamanhoController in 'Tamanho\Cadastro\uCadastroTamanhoController.pas',
  uCadastroTamanhoDto in 'Tamanho\Cadastro\uCadastroTamanhoDto.pas',
  uCadastroTamanhoForm in 'Tamanho\Cadastro\uCadastroTamanhoForm.pas' {CadastroTamanhoForm},
  uCadastroTamanhoModel in 'Tamanho\Cadastro\uCadastroTamanhoModel.pas',
  uCadastroTamanhoRegra in 'Tamanho\Cadastro\uCadastroTamanhoRegra.pas',
  uInterfaceCadastroTamanhoModel in 'Tamanho\Cadastro\uInterfaceCadastroTamanhoModel.pas',
  uConsultaTamanhoController in 'Tamanho\Consulta\uConsultaTamanhoController.pas',
  uConsultaTamanhoForm in 'Tamanho\Consulta\uConsultaTamanhoForm.pas' {ConsultaTamanhoForm},
  uConsultaTamanhoModel in 'Tamanho\Consulta\uConsultaTamanhoModel.pas',
  uConsultaTamanhoRegra in 'Tamanho\Consulta\uConsultaTamanhoRegra.pas',
  uInterfaceConsultaTamanhoModel in 'Tamanho\Consulta\uInterfaceConsultaTamanhoModel.pas',
  uInterfaceTamanhoModel in 'Tamanho\Consulta\uInterfaceTamanhoModel.pas',
  uCadastroModeloController in 'Modelo\Cadastro\uCadastroModeloController.pas',
  uCadastroModeloDto in 'Modelo\Cadastro\uCadastroModeloDto.pas',
  uCadastroModeloForm in 'Modelo\Cadastro\uCadastroModeloForm.pas' {CadastroModeloForm},
  uCadastroModeloModel in 'Modelo\Cadastro\uCadastroModeloModel.pas',
  uCadastroModeloRegra in 'Modelo\Cadastro\uCadastroModeloRegra.pas',
  uInterfaceCadastroModeloModel in 'Modelo\Cadastro\uInterfaceCadastroModeloModel.pas',
  uConsultaModeloController in 'Modelo\Consulta\uConsultaModeloController.pas',
  uConsultaModeloForm in 'Modelo\Consulta\uConsultaModeloForm.pas' {ConsultaModeloForm},
  uConsultaModeloModel in 'Modelo\Consulta\uConsultaModeloModel.pas',
  uConsultaModeloRegra in 'Modelo\Consulta\uConsultaModeloRegra.pas',
  uInterfaceConsultaModeloModel in 'Modelo\Consulta\uInterfaceConsultaModeloModel.pas',
  uInterfaceModeloModel in 'Modelo\Consulta\uInterfaceModeloModel.pas',
  uCor_ModeloModel in 'Cor_Modelo\uCor_ModeloModel.pas',
  uInterfaceCor_ModeloModel in 'Cor_Modelo\uInterfaceCor_ModeloModel.pas',
  uListaCores in 'Cor\uListaCores.pas',
  uCadastroMunicipioController in 'Municipio\cadastro\uCadastroMunicipioController.pas',
  uCadastroMunicipioDto in 'Municipio\cadastro\uCadastroMunicipioDto.pas',
  uCadastroMunicipioForm in 'Municipio\cadastro\uCadastroMunicipioForm.pas' {CadastroMunicipioForm},
  uCadastroMunicipioModel in 'Municipio\cadastro\uCadastroMunicipioModel.pas',
  uCadastroMunicipioRegra in 'Municipio\cadastro\uCadastroMunicipioRegra.pas',
  uInterfaceCadastroMunicipioModel in 'Municipio\cadastro\uInterfaceCadastroMunicipioModel.pas',
  uConsultaMunicipioController in 'Municipio\consulta\uConsultaMunicipioController.pas',
  uConsultaMunicipioForm in 'Municipio\consulta\uConsultaMunicipioForm.pas' {ConsultaMunicipioForm},
  uConsultaMunicipioModel in 'Municipio\consulta\uConsultaMunicipioModel.pas',
  uConsultaMunicipioRegra in 'Municipio\consulta\uConsultaMunicipioRegra.pas',
  uInterfaceConsultaMunicipioModel in 'Municipio\consulta\uInterfaceConsultaMunicipioModel.pas',
  uInterfaceMunicipioModel in 'Municipio\consulta\uInterfaceMunicipioModel.pas';

{$R *.res}


begin
  Application.Initialize;
  Application.MainFormOnTaskbar := True;
  Application.CreateForm(TfrmPrincipal, frmPrincipal);
  Application.Run;
end.
