program CamisasFelizes;

uses
  Vcl.Forms,
  uConexao in 'ConexãoBD\uConexao.pas',
  uConexaoSingleTon in 'ConexãoBD\uConexaoSingleTon.pas',
  uPrincipal in 'Principal\uPrincipal.pas' {frmPrincipal},
  uCadastroCorController in 'Cor\Cadastro\uCadastroCorController.pas',
  uCadastroCorDto in 'Cor\Cadastro\uCadastroCorDto.pas',
  uCadastroCorForm in 'Cor\Cadastro\uCadastroCorForm.pas' {CadastroCorForm},
  uCadastroCorModel in 'Cor\Cadastro\uCadastroCorModel.pas',
  uCadastroCorRegra in 'Cor\Cadastro\uCadastroCorRegra.pas',
  uInterfaceCadastroCorModel in 'Cor\Cadastro\uInterfaceCadastroCorModel.pas',
  uConsultaCorController in 'Cor\Consulta\uConsultaCorController.pas',
  uConsultaCorForm in 'Cor\Consulta\uConsultaCorForm.pas' {ConsultaCorForma},
  uConsultaCorModel in 'Cor\Consulta\uConsultaCorModel.pas',
  uConsultaCorRegra in 'Cor\Consulta\uConsultaCorRegra.pas',
  uInterfaceConsultaCorModel in 'Cor\Consulta\uInterfaceConsultaCorModel.pas',
  Vcl.Themes,
  Vcl.Styles,
  uCadastroTamanhoController in 'Tamanho\Cadastro\uCadastroTamanhoController.pas',
  uCadastroTamanhoDto in 'Tamanho\Cadastro\uCadastroTamanhoDto.pas',
  uCadastroTamanhoForm in 'Tamanho\Cadastro\uCadastroTamanhoForm.pas' {CadastroTamanhoForm},
  uCadastroTamanhoModel in 'Tamanho\Cadastro\uCadastroTamanhoModel.pas',
  uCadastroTamanhoRegra in 'Tamanho\Cadastro\uCadastroTamanhoRegra.pas',
  uInterfaceCadastroTamanhoModel in 'Tamanho\Cadastro\uInterfaceCadastroTamanhoModel.pas',
  uConsultaTamanhoController in 'Tamanho\Consulta\uConsultaTamanhoController.pas',
  uConsultaTamanhoModel in 'Tamanho\Consulta\uConsultaTamanhoModel.pas',
  uConsultaTamanhoRegra in 'Tamanho\Consulta\uConsultaTamanhoRegra.pas',
  uInterfaceConsultaTamanhoModel in 'Tamanho\Consulta\uInterfaceConsultaTamanhoModel.pas',
  uInterfaceTamanhoModel in 'Tamanho\Consulta\uInterfaceTamanhoModel.pas',
  uConsultaTamanhoForm in 'Tamanho\Consulta\uConsultaTamanhoForm.pas' {ConsultaTamanhoForm},
  uCadastroModeloController in 'Modelo\Cadastro\uCadastroModeloController.pas',
  uCadastroModeloDto in 'Modelo\Cadastro\uCadastroModeloDto.pas',
  uCadastroModeloForm in 'Modelo\Cadastro\uCadastroModeloForm.pas' {CadastroModeloForm},
  uCadastroModeloModel in 'Modelo\Cadastro\uCadastroModeloModel.pas',
  uCadastroModeloRegra in 'Modelo\Cadastro\uCadastroModeloRegra.pas',
  uInterfaceCadastroModeloModel in 'Modelo\Cadastro\uInterfaceCadastroModeloModel.pas',
  uConsultaModeloController in 'Modelo\Consulta\uConsultaModeloController.pas',
  uConsultaModeloForm in 'Modelo\Consulta\uConsultaModeloForm.pas' {ConsultaModeloForm},
  uConsultaModeloModel in 'Modelo\Consulta\uConsultaModeloModel.pas',
  uConsultaModeloRegra in 'Modelo\Consulta\uConsultaModeloRegra.pas',
  uInterfaceConsultaModeloModel in 'Modelo\Consulta\uInterfaceConsultaModeloModel.pas',
  uInterfaceCor_ModeloModel in 'Cor_Modelo\uInterfaceCor_ModeloModel.pas',
  uCor_ModeloModel in 'Cor_Modelo\uCor_ModeloModel.pas',
  uListaCores in 'Cor\uListaCores.pas',
  uBase in 'Base\Cadastro\uBase.pas' {frmBase},
  uClasseInterfaceViewBase in 'Base\Cadastro\uClasseInterfaceViewBase.pas',
  uInterfaceViewBase in 'Base\Cadastro\uInterfaceViewBase.pas',
  uClasseInterfaceConsultaBase in 'Base\Consulta\uClasseInterfaceConsultaBase.pas',
  uConsultaBase in 'Base\Consulta\uConsultaBase.pas' {frmPesquisaBase},
  uInterfaceConsultaBase in 'Base\Consulta\uInterfaceConsultaBase.pas',
  uCadastroUfController in 'CadastroUF\cadastro\uCadastroUfController.pas',
  uCadastroUfDto in 'CadastroUF\cadastro\uCadastroUfDto.pas',
  uCadastroUfForm in 'CadastroUF\cadastro\uCadastroUfForm.pas' {CadastroUfForm},
  uCadastroUfModel in 'CadastroUF\cadastro\uCadastroUfModel.pas',
  uCadastroUfRegra in 'CadastroUF\cadastro\uCadastroUfRegra.pas',
  uInterfaceCadastroUfModel in 'CadastroUF\cadastro\uInterfaceCadastroUfModel.pas',
  uConsultaUfController in 'CadastroUF\consulta\uConsultaUfController.pas',
  uConsultaUfForm in 'CadastroUF\consulta\uConsultaUfForm.pas' {ConsultaUfForm},
  uConsultaUfModel in 'CadastroUF\consulta\uConsultaUfModel.pas',
  uConsultaUfRegra in 'CadastroUF\consulta\uConsultaUfRegra.pas',
  uInterfaceConsultaUfModel in 'CadastroUF\consulta\uInterfaceConsultaUfModel.pas',
  uInterfaceUfModel in 'CadastroUF\consulta\uInterfaceUfModel.pas',
  uConsultaPedidoController in 'Pedido\Consulta\uConsultaPedidoController.pas',
  uConsultaPedidoForm in 'Pedido\Consulta\uConsultaPedidoForm.pas' {ConsultaPedidoForm},
  uConsultaPedidoModel in 'Pedido\Consulta\uConsultaPedidoModel.pas',
  uConsultaPedidoRegra in 'Pedido\Consulta\uConsultaPedidoRegra.pas',
  uInterfaceConsultaPedidoModel in 'Pedido\Consulta\uInterfaceConsultaPedidoModel.pas',
  uInterfacePedidoModel in 'Pedido\Consulta\uInterfacePedidoModel.pas',
  uCadastroPedidoController in 'Pedido\Cadastro\uCadastroPedidoController.pas',
  uCadastroPedidoDto in 'Pedido\Cadastro\uCadastroPedidoDto.pas',
  uCadastroPedidoForm in 'Pedido\Cadastro\uCadastroPedidoForm.pas' {CadastroPedidoForm},
  uCadastroPedidoModel in 'Pedido\Cadastro\uCadastroPedidoModel.pas',
  uCadastroPedidoRegra in 'Pedido\Cadastro\uCadastroPedidoRegra.pas',
  uInterfaceCadastroPedidoModel in 'Pedido\Cadastro\uInterfaceCadastroPedidoModel.pas',
  uInterfaceRelatorioModel in 'Relatorio\Pedidos\uInterfaceRelatorioModel.pas',
  uRelatorioController in 'Relatorio\Pedidos\uRelatorioController.pas',
  uRelatorioDto in 'Relatorio\Pedidos\uRelatorioDto.pas',
  uRelatorioForm in 'Relatorio\Pedidos\uRelatorioForm.pas' {FrmRelatorio},
  uRelatorioModel in 'Relatorio\Pedidos\uRelatorioModel.pas',
  uConsultaClienteController in 'Cliente\consulta\uConsultaClienteController.pas',
  uConsultaClienteForm in 'Cliente\consulta\uConsultaClienteForm.pas' {ConsultaClienteForm},
  uConsultaClienteModel in 'Cliente\consulta\uConsultaClienteModel.pas',
  uConsultaClienteRegra in 'Cliente\consulta\uConsultaClienteRegra.pas',
  uInterfaceConsultaClienteModel in 'Cliente\consulta\uInterfaceConsultaClienteModel.pas',
  uCadastroClienteDto in 'Cliente\cadastro\uCadastroClienteDto.pas',
  uCadastroClienteModel in 'Cliente\cadastro\uCadastroClienteModel.pas',
  uInterfaceCadastroClienteModel in 'Cliente\cadastro\uInterfaceCadastroClienteModel.pas',
  uCadastroEnderecoDto in 'Endereço\uCadastroEnderecoDto.pas',
  uCadastroEnderecoModel in 'Endereço\uCadastroEnderecoModel.pas',
  uInterfaceCadastroEnderecoModel in 'Endereço\uInterfaceCadastroEnderecoModel.pas',
  uCadastroBairroDto in 'Bairro\uCadastroBairroDto.pas',
  uCadastroBairroModel in 'Bairro\uCadastroBairroModel.pas',
  uInterfaceCadastroBairroModel in 'Bairro\uInterfaceCadastroBairroModel.pas',
  uCadastroMunicipioDto in 'Municipio\uCadastroMunicipioDto.pas',
  uCadastroMunicipioModel in 'Municipio\uCadastroMunicipioModel.pas',
  uInterfaceCadastroMunicipioModel in 'Municipio\uInterfaceCadastroMunicipioModel.pas';

{$R *.res}


begin
  Application.Initialize;
  Application.MainFormOnTaskbar := True;
  Application.CreateForm(TfrmPrincipal, frmPrincipal);
  Application.Run;
end.
